### ISSUE TITLE
Bone morphometry (BM) feature set computation error

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/BoneTextureExtension#25]
Slicer version: 4.11.0-2019-12-02 r28659

```
Traceback (most recent call last):
  File "/home/bpaniagua/.config/NA-MIC/Extensions-28659/BoneTextureExtension/lib/Slicer-4.11/qt-scripted-modules/BoneTexture.py", line 210, in onComputeFeatures
    self.BMFeaturesValueDict)
  File "/home/bpaniagua/.config/NA-MIC/Extensions-28659/BoneTextureExtension/lib/Slicer-4.11/qt-scripted-modules/BoneTexture.py", line 363, in computeFeatures
    BMFeaturesValueDict)
  File "/home/bpaniagua/.config/NA-MIC/Extensions-28659/BoneTextureExtension/lib/Slicer-4.11/qt-scripted-modules/BoneTexture.py", line 379, in computeSingleFeatureSet
    return list(map(float, CLI.GetParameterValue(2, 0).split(",")))
ValueError: could not convert string to float: 
```

**Comment by phcerdan** [comment]
Umm, that line is actually commented out in master. I think Slicer is using the nightly branch instead of master.

Opening https://github.com/Slicer/ExtensionsIndex/pull/1667 to fix it.

**Comment by bpaniagua** [comment]
Thank you so much, @phcerdan !
