### ISSUE TITLE
Bone texture extension is failing due to lack of LabelStatistics module

### ISSUE THREAD

**Issue by SlicerMorph** [Kitware/BoneTextureExtension#39]
This is from a recent preview (4.13.0-2021-12-22 r30513 / 0a65de7). Isn't labelStatistics deprecated? Is there a reason why BoneTexture extension is still using labelmaps, as opposed to segmentations which is now the default in slicer?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\murat\AppData\Local\NA-MIC\Slicer 4.13.0-2021-12-22\lib\Python\Lib\imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/murat/AppData/Local/NA-MIC/Slicer 4.13.0-2021-12-22/NA-MIC/Extensions-30513/BoneTextureExtension/lib/Slicer-4.13/qt-scripted-modules/BoneTexture.py", line 9, in <module>
    from LabelStatistics import LabelStatisticsLogic
ModuleNotFoundError: No module named 'LabelStatistics'
```

**Comment by jcfr** [comment]
cc: @bpaniagua @allemangD
